AWSTemplateFormatVersion: '2010-09-09'
Description: This creates an EC2 Instance with passing parameters

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
    Description: EC2 instance type
  ImageId:
    Type: AWS::EC2::Image::Id
    Description: AMI ID to use for the instance
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet in which to launch the instance
  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group for the instance

Resources:
  MyEc2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: '!Ref InstanceType'
      ImageId: '!Ref ImageId'
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: '0'
          SubnetId: '!Ref SubnetId'
          GroupSet:
            - '!Ref SecurityGroupId'